bluegreen:
    replicaCount: 5

    image:
        repository: nginx
        tag: 1.15.5

    service:
        type: NodePort

    ingress:
        enabled: true
        annotations:
            kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
        hosts:
        - host: example-helm-app.kubernetes.local
          paths: 
          - path: /
            backend:
                serviceName: {{ include "bluegreen.fullname" . }}-active
                servicePort: 80
        - host: example-helm-app-preview.kubernetes.local
          paths: 
          - path: /
            backend:
                serviceName: {{ include "bluegreen.fullname" . }}-preview
                servicePort: 80
    