bluegreen:
    replicaCount: 1

    image:
        repository: adybfjcns/python-microservice
        tag: dind-94b7e06

    #service:
    #    type: NodePort
    #    port: 5000

    ingress:
        enabled: true
        annotations:
            kubernetes.io/ingress.class: nginx
            ingress.kubernetes.io/rewrite-target: /

        activeHosts:           
        - host: example-helm-app-bluegreen.kubernetes.local
          paths: 
            - /

        previewHosts:           
        - host: example-helm-app-bluegreen-preview.kubernetes.local
          paths: 
            - /

demo:
    replicaCount: 1

    image:
        repository: adybfjcns/python-microservice
        tag: kaniko-94b7e06

    #service:
    #    type: NodePort
    #    port: 5000

    ingress:
        enabled: true
        annotations:
            kubernetes.io/ingress.class: nginx
            ingress.kubernetes.io/rewrite-target: /

        hosts:           
        - host: example-helm-app-demo.kubernetes.local
          paths: 
            - /
 